name: Unzip and Commit ZIP file

on:
  workflow_dispatch:

jobs:
  unzip_and_commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository content
      uses: actions/checkout@v2

    - name: Install unzip
      run: sudo apt-get install unzip

    - name: Unzip the .zip file
      run: unzip muie.zip -d output_directory/

    - name: Set Git user
      run: |
        git config --global user.name 'Your Name'
        git config --global user.email 'your-email@example.com'

    - name: Mark repository as safe
      run: git config --global --add safe.directory /home/runner/work/na/na

    - name: Add and commit unzipped files
      run: |
        git add output_directory/*
        git commit -m "Added unzipped content"
        git push
